nomFichier = '7wonders_original.jpg';
image = imread(nomFichier);
ajouterBDD(image, pic2data(image), '7 Wonders', 'bddtest.mat');
nomFichier = 'abyss_original.jpg';
image = imread(nomFichier);
ajouterBDD(image, pic2data(image), 'Abyss', 'bddtest.mat');
nomFichier = 'mr_jack_original.jpg';
image = imread(nomFichier);
ajouterBDD(image, pic2data(image), 'mr_jack', 'bddtest.mat');
nomFichier = 'seasons_original.jpg';
image = imread(nomFichier);
ajouterBDD(image, pic2data(image), 'seasons', 'bddtest.mat');
nomFichier = 'takenoko_original.jpg';
image = imread(nomFichier);
ajouterBDD(image, pic2data(image), 'takenoko', 'bddtest.mat');
nomFichier = 'kids_of_london_original.jpg';
image = imread(nomFichier);
ajouterBDD(image, pic2data(image), 'kids_of_london', 'bddtest.mat');
nomFichier = 'whitechapel_original.jpg';
image = imread(nomFichier);
ajouterBDD(image, pic2data(image), 'whitechapel', 'bddtest.mat');
