nomFichier = 'abyss_original.jpg';
image = imread(nomFichier);
ajouterBDD(image, pic2data(image), 'Abyss', 'bddtest.mat');
nomFichier = 'mr_jack_original.jpg';
image = imread(nomFichier);
ajouterBDD(image, pic2data(image), 'mr_jack', 'bddtest.mat');
nomFichier = 'seasons_original.jpg';
image = imread(nomFichier);
ajouterBDD(image, pic2data(image), 'seasons', 'bddtest.mat');
nomFichier = 'kids_of_london_original.jpg';
image = imread(nomFichier);
ajouterBDD(image, pic2data(image), 'kids_of_london', 'bddtest.mat');
nomFichier = 'whitechapel_original.jpg';
image = imread(nomFichier);
ajouterBDD(image, pic2data(image), 'whitechapel', 'bddtest.mat');
nomFichier = 'whitehall_original.jpg';
image = imread(nomFichier);
ajouterBDD(image, pic2data(image), 'whitehall', 'bddtest.mat');
nomFichier = 'takenoko_original.jpg';
image = imread(nomFichier);
ajouterBDD(image, pic2data(image), 'takenoko', 'bddtest.mat');
nomFichier = 'pandemie_original.jpg';
image = imread(nomFichier);
ajouterBDD(image, pic2data(image), 'pandemie', 'bddtest.mat');
nomFichier = 'onirim_original.jpg';
image = imread(nomFichier);
ajouterBDD(image, pic2data(image), 'onirim', 'bddtest.mat');
nomFichier = 'loony_quest_original.jpg';
image = imread(nomFichier);
ajouterBDD(image, pic2data(image), 'loony_quest', 'bddtest.mat');
nomFichier = 'iknow_original.jpg';
image = imread(nomFichier);
ajouterBDD(image, pic2data(image), 'iknow', 'bddtest.mat');
nomFichier = 'catane_original.jpg';
image = imread(nomFichier);
ajouterBDD(image, pic2data(image), 'catane', 'bddtest.mat');
nomFichier = 'bazar_bizarre_original.jpg';
image = imread(nomFichier);
ajouterBDD(image, pic2data(image), 'bazar_bizarre', 'bddtest.mat');